services:
  mysql:
    container_name: microservice_mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: testUser
      MYSQL_USER: testUser
      MYSQL_PASSWORD: testUser
      MYSQL_DATABASE: inventory
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - microservices-network

  phpmyadmin:
    container_name: microservice_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: microservice_mysql
      MYSQL_ROOT_PASSWORD: testUser
    ports:
      - "8083:80"
    restart: unless-stopped
    networks:
      - microservices-network

  keycloak:
    container_name: microservice_keycloak
    image: quay.io/keycloak/keycloak:26.0.6
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"  # Expose port for Keycloak
    restart: unless-stopped
    networks:
      - microservices-network
    command: [ "start-dev" ]  # Starts Keycloak in development mode

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:latest
    environment:
      - ZIPKIN_ZIPKIN_HTTP_SOURCE=/data
    ports:
      - "9411:9411"  # Exposing Zipkin on port 9411
    restart: unless-stopped
    networks:
      - microservices-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1



networks:
  microservices-network:

volumes:
  mysql_data: